### ISSUE TITLE
Want to add a dope readme

### ISSUE THREAD

**Issue by iamrahulmahato** [Design-and-Code/Dope-Github-Readmes#55] opened 2022-03-10 15:31 UTC
Can i add my design readme file

**Comment by DevrajDC** [comment] 2022-03-10 15:34
What do you mean by Design readme file?

**Comment by iamrahulmahato** [comment] 2022-03-10 15:36
@DevrajDC yes

**Comment by iamrahulmahato** [comment] 2022-03-11 13:49
@DevrajDC The PR is made #56  . Kindly review and merge it.
Thank You

**Comment by Greeshma2903** [comment] 2022-03-12 07:22
Hello @iamrahulmahato, you can directly open a PR for your next contribution, we'll review it there and merge it accordingly. Closing this issue for now. 🙂

**Closed by Greeshma2903** 2022-03-12 07:22 UTC
